// Generated by https://quicktype.io

export interface Centtra3DTO {
    desctra3: string;
    id:       ID;
    idCentro: number;
    idPadre:  number;
    orden:    number;
}

export interface ID {
    centtra1: string;
    centtra2: string;
    centtra3: string;
    codienti: number;
}
