// Generated by https://quicktype.io

export interface Centtra1DTO {
    desctra1: string;
    ffin:     string;
    finicio:  string;
    id:       ID;
    idCentro: number;
    orden:    number;
}

export interface ID {
    centtra1: string;
    codienti: number;
}
