// Generated by https://quicktype.io

export class YFasePuesDTO {
    fcrefase: Date | null;
    fechpose: Date | null;
    fechcese: Date | null;
    fexpcese: Date | null;
    porcdedi: Number;
    codiempl: Number;
    id:       YFasePuesDTOID;
    constructor() {
        this.fcrefase = null;
        this.fechpose =null;
        this.fechcese =null;
        this.fexpcese=null;
        this.codiempl=0;
        this.porcdedi=100;
        this.id = new YFasePuesDTOID();

    }
}

export class  YFasePuesDTOID {
    codienti: number;
    codipues: number;
    coditrpt: string;
    numedota: number;
    numefase: number;
    constructor() {
        this.codienti= 0;
        this.codipues= 0;
        this.coditrpt= '';
        this.numedota= 0;
        this.numefase= 0;
    }
}
